import { configureStore } from "@reduxjs/toolkit";
import { authSlice } from "./auth/authSlice";
import {
    coordinadorSlice,
    dashboardSlice,
    escaneadorSlice,
    jrvmovilSlice,
    juntaSlice,
    reconteoSlice,
    roleSlice,
    stateSlice,
    supervisorSlice,
    uiCoordinadorSlice,
    uiDashboardSlice,
    uiEscaneadorSlice,
    uiJrvmovilSlice,
    uiReconteoSlice,
    uiSupervisorSlice,
    uiUsuarioSlice,
    uiVeedorSlice,
    usuarioSlice,
    veedorSlice,
} from "./app";

export const store = configureStore({
    reducer: {
        auth: authSlice.reducer,
        role: roleSlice.reducer,
        dashboard: dashboardSlice.reducer,
        uiDashboard: uiDashboardSlice.reducer,
        usuario: usuarioSlice.reducer,
        state: stateSlice.reducer,
        junta: juntaSlice.reducer,
        uiUsuario: uiUsuarioSlice.reducer,
        supervisor: supervisorSlice.reducer,
        uiSupervisor: uiSupervisorSlice.reducer,
        coordinador: coordinadorSlice.reducer,
        uiCoordinador: uiCoordinadorSlice.reducer,
        veedor: veedorSlice.reducer,
        uiVeedor: uiVeedorSlice.reducer,
        jrvmovil: jrvmovilSlice.reducer,
        uiJrvmovil: uiJrvmovilSlice.reducer,
        reconteo: reconteoSlice.reducer,
        uiReconteo: uiReconteoSlice.reducer,
        escaner: escaneadorSlice.reducer,
        uiEscaner: uiEscaneadorSlice.reducer,
    },
});
